CATEGORY_SPECS = {
    "computer": [
        "is_notebook",
        "motherboard",
        "cpu",
        "ram",
        "storage",
        "gpu",
        "inches",
        "panel_type",
        "resolution",
        "refresh_rate",
        "color_support",
        "output",
    ],
    "gpu": ["model", "vram", "chipset", "max_resolution", "output", "tech_support"],
    "ram": ["model", "capacity", "ddr", "speed"],
    "cpu": [
        "model",
        "integrated_video",
        "socket",
        "core_number",
        "thread_number",
        "frequency",
        "mem_speed",
    ],
    "motherboard": [
        "model",
        "socket",
        "chipset",
        "form_type",
        "max_ram_capacity",
        "ram_type",
        "ram_slots",
        "pcie_slots",
        "sata_ports",
        "m2_slot",
    ],
    "keyboard": ["model", "key_type", "layout", "connectivity", "dimension"],
    "mouse": ["model", "dpi", "connectivity", "color"],
    "monitor": [
        "model",
        "inches",
        "panel_type",
        "proportion",
        "resolution",
        "refresh_rate",
        "color_support",
        "output",
    ],
    "storage": [
        "model",
        "capacity_gb",
        "storage_type",
        "interface",
        "form_factor",
        "read_speed",
        "write_speed",
    ],
}
