# Generated by Django 5.1.9 on 2025-06-13 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gamer', 'Gamer'), ('home_office', 'Home Office'), ('estudo', 'Estudo')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
