# Generated by Django 5.1.9 on 2025-06-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
