# Generated by Django 5.1.9 on 2025-06-22 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_specification_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=100)),
                ('form_type', models.CharField(max_length=50)),
                ('max_ram_capacity', models.IntegerField()),
                ('ram_type', models.CharField(max_length=10)),
                ('ram_slots', models.IntegerField()),
                ('pcie_slots', models.PositiveIntegerField()),
                ('sata_ports', models.IntegerField()),
                ('m2_slot', models.IntegerField()),
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
