# Generated by Django 5.2.3 on 2025-06-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_motherboard_delete_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='brand',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='model',
            field=models.CharField(default='Generic Model', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='hash',
            field=models.TextField(default='name+product_url'),
        ),
        migrations.AddField(
            model_name='productstore',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='store',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('computer', 'Computer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('motherboard', 'Motherboard'), ('ram', 'Ram'), ('gpu', 'Gpu'), ('storage', 'Storage')], max_length=20),
        ),
    ]
