# Generated by Django 5.2.3 on 2025-06-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_insert_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('computer', 'Computer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('motherboard', 'Motherboard'), ('ram', 'Ram'), ('gpu', 'Gpu'), ('cpu', 'Cpu')], max_length=20),
        ),
    ]
