# Generated by Django 5.2.3 on 2025-07-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_mouse_brand_remove_ram_brand_and_more'),
        ('api', '0008_alter_product_category'),
    ]

    operations = [
    ]
