# Generated by Django 5.2.3 on 2025-07-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250630_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('computer', 'Computer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('motherboard', 'Motherboard'), ('ram', 'Ram'), ('gpu', 'Gpu'), ('cpu', 'Cpu'), ('storage', 'Storage')], max_length=20),
        ),
    ]
