# Generated by Django 5.2.3 on 2025-07-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_list_user_remove_productlist_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecification',
            name='cooler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='psu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
