# Generated by Django 5.2.3 on 2025-07-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userspecification_cooler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_gb', models.CharField(help_text='Capacidade em GB', max_length=255)),
                ('storage_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe')], max_length=255)),
                ('interface', models.CharField(choices=[('SATA', 'SATA'), ('PCIe', 'PCIe'), ('USB', 'USB')], max_length=255)),
                ('form_factor', models.CharField(help_text='Ex: 2.5, 3.5, M.2', max_length=255)),
                ('read_speed', models.CharField(help_text='Velocidade de leitura em MB/s (opcional)', max_length=255, null=True)),
                ('write_speed', models.CharField(help_text='Velocidade de gravação em MB/s (opcional)', max_length=255, null=True)),
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='api.product')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
    ]
