# Generated by Django 5.2.3 on 2025-07-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='brand',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
