# Generated by Django 5.2.3 on 2025-07-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
