# Generated by Django 5.2.3 on 2025-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mouse_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='brand',
            field=models.CharField(default='Generic Brand', max_length=255),
        ),
    ]
