# Generated by Django 5.2.3 on 2025-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='read_speed',
            field=models.CharField(default='', help_text='Velocidade de leitura em MB/s (opcional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='write_speed',
            field=models.CharField(default='', help_text='Velocidade de gravação em MB/s (opcional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='cooler',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='gpu',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='psu',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
