# Generated by Django 5.2.3 on 2025-07-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_mouse_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='brand',
        ),
    ]
