# Generated by Django 5.2.3 on 2025-07-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_computer_inches_alter_computer_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='color_support',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='gpu',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='inches',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='output',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='panel_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='refresh_rate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='integrated_video',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='mem_speed',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='thread_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='max_resolution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='output',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tech_support',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='connectivity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='dimension',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='key_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='color_support',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='inches',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='panel_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='proportion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='refresh_rate',
            field=models.CharField(blank=True, default='60hz', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='m2_slot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='max_ram_capacity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='pcie_slots',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='sata_ports',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='connectivity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='dpi',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ddr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ram',
            name='speed',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='read_speed',
            field=models.CharField(blank=True, default='', help_text='Velocidade de leitura em MB/s (opcional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='storage',
            name='write_speed',
            field=models.CharField(blank=True, default='', help_text='Velocidade de gravação em MB/s (opcional)', max_length=255),
        ),
    ]
