# Generated by Django 5.2.3 on 2025-07-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_product_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='computer',
            index=models.Index(fields=['cpu', 'gpu', 'ram', 'panel_type'], name='api_compute_cpu_32933f_idx'),
        ),
        migrations.AddIndex(
            model_name='cpu',
            index=models.Index(fields=['core_number', 'frequency'], name='api_cpu_core_nu_1c9d69_idx'),
        ),
        migrations.AddIndex(
            model_name='gpu',
            index=models.Index(fields=['vram'], name='api_gpu_vram_bc688e_idx'),
        ),
        migrations.AddIndex(
            model_name='keyboard',
            index=models.Index(fields=['key_type'], name='api_keyboar_key_typ_1087a4_idx'),
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['panel_type', 'inches', 'refresh_rate'], name='api_monitor_panel_t_3d3d60_idx'),
        ),
        migrations.AddIndex(
            model_name='motherboard',
            index=models.Index(fields=['socket', 'form_type', 'ram_type'], name='api_motherb_socket_6cb34e_idx'),
        ),
        migrations.AddIndex(
            model_name='mouse',
            index=models.Index(fields=['connectivity'], name='api_mouse_connect_13d575_idx'),
        ),
        migrations.AddIndex(
            model_name='ram',
            index=models.Index(fields=['speed', 'ddr'], name='api_ram_speed_45aedc_idx'),
        ),
        migrations.AddIndex(
            model_name='storage',
            index=models.Index(fields=['capacity_gb', 'storage_type'], name='api_storage_capacit_c9f508_idx'),
        ),
    ]
