# Generated by Django 5.2.3 on 2025-07-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_default_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(default='', max_length=10),
        ),
    ]
