# Generated by Django 5.2.3 on 2025-07-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_mouse_brand'),
        ('api', '0026_populate_subscription_details'),
    ]

    operations = [
    ]
