# Generated by Django 5.2.3 on 2025-07-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='build',
        ),
        migrations.AddField(
            model_name='preference',
            name='build',
            field=models.ManyToManyField(blank=True, to='api.product'),
        ),
    ]
