# Generated by Django 5.2.3 on 2025-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_preference_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reputation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reputation_source', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
