# Generated by Django 5.2.3 on 2025-07-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_storereputation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storereputation',
            unique_together={('name', 'reputation_source')},
        ),
    ]
